#!/usr/bin/python
import sys
import os
from subprocess import call

files = os.listdir(sys.argv[1]);

for name in files:
    n = name.split(".");
    iname = "%s%s" % (sys.argv[1],name);
    oname = "%s%s.wav" % (sys.argv[2],n[0]);
    cmd = "ffmpeg -i '%s' -map_metadata -1 -fflags +bitexact -flags:v +bitexact -flags:a +bitexact '%s' &"% (iname,oname);
    call(cmd, shell=True);


print ("Done\n");
